"use client";

export interface Product {
    name: string;
    rate: string;
    image?: string;
    category?: string;
    description?: string;
    tags?: string[];
    id?: string;
    price?: string | number;
}

export const products: Product[] = [
    { name: "Apricot Oil", rate: "850/-", image: "/images/products/apricot-oil.jpg" },
    { name: "Anethol", rate: "1450/-", image: "/images/products/anethol.jpg" },
    { name: "Ajowain Oil", rate: "950/1800" },
    { name: "Almond Oil 5%", rate: "450/-" },
    { name: "Avocado Oil", rate: "1200/-" },
    { name: "Anise Oil", rate: "1400/-" },
    { name: "Argan Oil", rate: "3100/-" },
    { name: "Basil Oil", rate: "2600/-" },
    { name: "Bergamot Oil", rate: "1050/-" },
    { name: "Black Pepper Oil", rate: "4800/-" },
    { name: "Bhimseni Kapoor", rate: "1250/-" },
    { name: "Cajuput Oil", rate: "950/-" },
    { name: "Camphor Oil", rate: "450/-" },
    { name: "Carrot Seed Oil", rate: "7900/-" },
    { name: "Cinnamon Oil", rate: "450/-" },
    { name: "Citronella Oil", rate: "1350/-" },
    { name: "Clove Oil (PG)", rate: "750/-" },
    { name: "Clove Leaf Oil", rate: "1750/-" },
    { name: "Cedar Wood Oil", rate: "1050/-" },
    { name: "Cumin Seed Oil", rate: "4850/-" },
    { name: "Curry Leaf Oil", rate: "14000/-" },
    { name: "Coriander Oil", rate: "8900/-" },
    { name: "Cardamom Oil", rate: "38000/-" },
    { name: "Camphor Powder", rate: "1050/-" },
    { name: "Cinnmon Life Oil", rate: "2950/-" },
    { name: "D-Limonene", rate: "1250/-" },
    { name: "Eucalyptus Oil", rate: "950/1200" },
    { name: "Evening Prime Rose", rate: "1275/-" },
    { name: "Eugenol Pure", rate: "1900/-" },
    { name: "Frankincense Myrrh", rate: "4200/-" },
    { name: "Geranium Oil", rate: "2550/3500" },
    { name: "Ginger Oil", rate: "9800/-" },
    { name: "Grape Seed Oil", rate: "1200/-" },
    { name: "Jojoba Oil/ Gold", rate: "1200/1550" },
    { name: "Lemon Grass Oil", rate: "1250/1600" },
    { name: "Lime Oil", rate: "1800/-" },
    { name: "Clove Bud Oil", rate: "3600/-" },
    { name: "Calamus Oil", rate: "8200/-" },
    { name: "Lavender Oil", rate: "1200/11000" },
    { name: "Lemon Oil", rate: "1400/-" },
    { name: "Menthol Crystal", rate: "1550/-" },
    { name: "Neroli Oil", rate: "5800/6800" },
    { name: "Neem Oil", rate: "450/-" },
    { name: "Nutmeg Oil", rate: "950/4500" },
    { name: "Olive Oil", rate: "480/-" },
    { name: "Orange Oil", rate: "1550/-" },
    { name: "Palmrosa Oil", rate: "2800/4300" },
    { name: "Patcholi Oil", rate: "7800/-" },
    { name: "Peppermint Oil", rate: "1350/-" },
    { name: "Rosemary Oil", rate: "1350/3400", image: "/images/products/rosemary-oil.jpg" },
    { name: "Spearmint Oil", rate: "3800/-", image: "/images/products/spearmint-oil.jpg" },
    { name: "Thyme Oil", rate: "3850/-", image: "/images/products/thyme-oil.jpg" },
    { name: "Tea Tree Oil", rate: "2600/4300", image: "/images/products/tea-tree-oil.jpg" },
    { name: "Turmeric Oil", rate: "1450/-", image: "/images/products/turmeric-oil.jpg" },
    { name: "Thymol Crystals", rate: "1150/-", image: "/images/products/thymol-crystals.jpg" },
    { name: "Vetivert Oil", rate: "2550/18000", image: "/images/products/vetiver-oil.jpg" },
    { name: "Ylang Ylang Oil", rate: "1700/7300", image: "/images/products/ylang-ylang-oil.jpg" },
    { name: "Wheat Germ Oil", rate: "450/-", image: "/images/products/wheat-germ-oil.jpg" },
    { name: "Methyl Salicylate", rate: "380/-", image: "/images/products/methyl-salicylate.jpg" },
    { name: "Terpentine Oil", rate: "260/-", image: "/images/products/turpentine-oil.jpg" },
    { name: "Walnut Oil", rate: "1650/-", image: "/images/products/walnut-oil.jpg" },
    { name: "Caraway Oil", rate: "2850/-", image: "/images/products/caraway-oil.jpg" },
    { name: "Cassia Oil", rate: "650/-" },
    { name: "Clary Sage", rate: "23500/-" },
    { name: "Mehandi Oil", rate: "560/-" },
    { name: "Kalonji Oil", rate: "950/1150" },
    { name: "Cade Oil", rate: "1350/-" },
    { name: "Nagarmotha Oil", rate: "24500/-" },
    { name: "Fennel Seed Oil", rate: "4850/-" },
    { name: "Dill Oil", rate: "2650/-" },
    { name: "Petitgrain Oil", rate: "8700/-" },
    { name: "Cypress Oil (Spain)", rate: "8900/-" },
    { name: "Mandarin Oil", rate: "16550/-" },
    { name: "Tulsi Oil", rate: "13500/-" },
    { name: "Calendula Oil", rate: "2600/-" },
    { name: "Cinnamon Bark Oil", rate: "2525/-" },
    { name: "Rose Hip", rate: "2250/-" },
];
